# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.10

    working_directory: ~/app

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: Install dependencies
          command: |
            npm cache clean --force
            npm install -f -d --quiet --loglevel=warn
      # Step 3: run linter and tests
      - run:
          name: Run test
          command: npm run-script test
