apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-deploy
spec:
  ports:
    - targetPort: 3000
      port: 80
  selector:
    app: test-deploy
    tier: backend
  type: LoadBalancer
